kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: example
spec:
  nodeSelector: null
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/jandradap/pipeline-build-test.git'
      ref: develop
  runPolicy: Serial
status:
